version: '2'
services:
  gimnasio-app:
    image: gimnasio
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://gimnasio-mysql:3306/gimnasio?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  gimnasio-mysql:
    extends:
      file: mysql.yml
      service: gimnasio-mysql
